---
schema:
  procedures: {}
  tables:
    user:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - email
          match_type: ''
          name: user_email
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - handle
          match_type: ''
          name: user_handle
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        email:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: email
          order: 3
          size:
            - 96
        handle:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: handle
          order: 2
          size:
            - 32
        password:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 4
          size:
            - 0
        user_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: user_id
          order: 1
          size:
            - 0
      indices: []
      name: user
      options: []
      order: 1
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    DBIx::Class::Schema: ~
    DBIx::Schema: ~
    package: &1 !!perl/hash:CatalystX::Example::Checklist::Schema
      class_mappings:
        CatalystX::Example::Checklist::Schema::Result::User: User
        DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult: __VERSION
      source_registrations:
        User: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            email:
              data_type: varchar
              size: 96
            handle:
              data_type: varchar
              size: 32
            password:
              _inflate_info:
                deflate: !!perl/code '{ "DUMMY" }'
                inflate: !!perl/code '{ "DUMMY" }'
              data_type: text
              inflate_passphrase: rfc2307
              passphrase: rfc2307
              passphrase_args:
                algorithm: SHA-1
                salt_random: 20
              passphrase_check_method: check_password
              passphrase_class: SaltedDigest
            user_id:
              data_type: integer
              is_auto_increment: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - user_id
            - handle
            - email
            - password
          _primaries: &2
            - user_id
          _relationships: {}
          _unique_constraints:
            primary: *2
            user_email:
              - email
            user_handle:
              - handle
          name: user
          result_class: CatalystX::Example::Checklist::Schema::Result::User
          resultset_attributes: {}
          resultset_class: CatalystX::Example::Checklist::Schema::ResultSet::User
          schema: *1
          source_name: User
        __VERSION: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            ddl:
              data_type: text
              is_nullable: 1
            id:
              data_type: int
              is_auto_increment: 1
            upgrade_sql:
              data_type: text
              is_nullable: 1
            version:
              data_type: varchar
              size: 50
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - version
            - ddl
            - upgrade_sql
          _primaries: &3
            - id
          _relationships: {}
          _unique_constraints:
            dbix_class_deploymenthandler_versions_version:
              - version
            primary: *3
          name: dbix_class_deploymenthandler_versions
          result_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult
          resultset_attributes: {}
          resultset_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResultSet
          schema: *1
          source_name: __VERSION
      storage: !!perl/hash:DBIx::Class::Storage::DBI::SQLite
        _conn_pid: 70427
        _connect_info:
          - DBI:SQLite:/Users/john/Desktop/CatalystX-Example-Checklist/share/catalystx-example-checklist-schema.db
          - ''
          - ''
        _dbh: !!perl/hash:DBI::db {}
        _dbh_autocommit: 1
        _dbh_details: {}
        _dbh_gen: 0
        _dbi_connect_info:
          - DBI:SQLite:/Users/john/Desktop/CatalystX-Example-Checklist/share/catalystx-example-checklist-schema.db
          - ''
          - ''
          - &4
            AutoCommit: 1
            PrintError: 0
            RaiseError: 1
            ShowErrorStatement: 1
        _dbic_connect_attributes: *4
        _driver_determined: 1
        _in_do_block: 0
        _sql_maker: ~
        _sql_maker_opts: {}
        savepoints: []
        schema: *1
        transaction_depth: 0
    sources:
      - User
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11016
